#!/bin/bash

# Bundle abc2svg modules into a single file

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENDOR_DIR="$SCRIPT_DIR/vendor/abc2svg"
OUTPUT_FILE="$VENDOR_DIR/abc2svg-bundle.js"

# Files to bundle
FILES=(
  "abc2svg-1.js"
  "chordnames-1.js"
  "MIDI-1.js"
  "strtab-1.js"
)

echo "=== Bundling abc2svg ==="
echo ""

# Check if source files exist
for file in "${FILES[@]}"; do
  if [ ! -f "$VENDOR_DIR/$file" ]; then
    echo "Error: $VENDOR_DIR/$file not found"
    exit 1
  fi
done

# Create bundle - just concatenate files
echo "Creating bundle..."

cat > "$OUTPUT_FILE" << 'EOF'
// abc2svg - Bundle
// Auto-generated by scripts/bundle-abc2svg.sh
// DO NOT EDIT MANUALLY

EOF

for file in "${FILES[@]}"; do
  cat "$VENDOR_DIR/$file" >> "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE"
done

echo "export default abc2svg" >> "$OUTPUT_FILE"

echo "✓ Bundle created: $OUTPUT_FILE"

# Show file size
BUNDLE_SIZE=$(wc -c < "$OUTPUT_FILE" | tr -d ' ')
echo "  Size: $BUNDLE_SIZE bytes"
echo ""
echo "✓ Done!"
